repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.20.0
    hooks:
      - id: toml-sort
  