from src.ch03_finance_logic._ref.ch03_keywords import *


class Ch04Keywords(str, Enum):
    BitNum = "BitNum"
    FundIota = "FundIota"
    FundNum = "FundNum"
    GrainFloat = "GrainFloat"
    GroupTitle = "GroupTitle"
    HealerName = "HealerName"
    INSERT = "INSERT"
    KnotTerm = "KnotTerm"
    LabelTerm = "LabelTerm"
    MomentLabel = "MomentLabel"
    MoneyUnit = "MoneyUnit"
    NameTerm = "NameTerm"
    NexusLabel = "NexusLabel"
    PennyNum = "PennyNum"
    RespectNum = "RespectNum"
    RopeTerm = "RopeTerm"
    TitleTerm = "TitleTerm"
    UPDATE = "UPDATE"
    VoiceName = "VoiceName"
    awardee_title = "awardee_title"
    awardunits = "awardunits"
    belief_name = "belief_name"
    credor_pool = "credor_pool"
    debtor_pool = "debtor_pool"
    fund_agenda_give = "fund_agenda_give"
    fund_agenda_ratio_give = "fund_agenda_ratio_give"
    fund_agenda_ratio_take = "fund_agenda_ratio_take"
    fund_agenda_take = "fund_agenda_take"
    fund_give = "fund_give"
    fund_iota = "fund_iota"
    fund_pool = "fund_pool"
    fund_take = "fund_take"
    give_force = "give_force"
    group_cred_points = "group_cred_points"
    group_debt_points = "group_debt_points"
    group_title = "group_title"
    groupunits = "groupunits"
    inallocable_voice_debt_points = "inallocable_voice_debt_points"
    irrational_voice_debt_points = "irrational_voice_debt_points"
    knot = "knot"
    laborheir = "laborheir"
    laborunit = "laborunit"
    magnitude = "magnitude"
    memberships = "memberships"
    parent_rope = "parent_rope"
    parent_solo = "parent_solo"
    party_title = "party_title"
    penny = "penny"
    rational = "rational"
    respect_bit = "respect_bit"
    solo = "solo"
    sqlite_datatype = "sqlite_datatype"
    take_force = "take_force"
    voice_cred_points = "voice_cred_points"
    voice_debt_points = "voice_debt_points"
    voice_name = "voice_name"

    def __str__(self):
        return self.value
