from src.a03_group_logic.test._util.a03_str import (
    credor_pool_str,
    debtor_pool_str,
    fund_agenda_give_str,
    fund_agenda_ratio_give_str,
    fund_agenda_ratio_take_str,
    fund_agenda_take_str,
    fund_give_str,
    fund_take_str,
    group_cred_points_str,
    group_debt_points_str,
    group_title_str,
    inallocable_voice_debt_points_str,
    irrational_voice_debt_points_str,
    memberships_str,
    voice_cred_points_str,
    voice_debt_points_str,
)
from src.a05_plan_logic.test._util.a05_str import (
    _healerunit_ratio_str,
    _is_expanded_str,
    _kids_str,
    _level_str,
    _range_evaluated_str,
    _reasonheirs_str,
    _stop_calc_str,
    _uid_str,
    active_hx_str,
    active_str,
    addin_str,
    all_voice_cred_str,
    all_voice_debt_str,
    awardheirs_str,
    awardlines_str,
    awardunits_str,
    begin_str,
    chore_str,
    close_str,
    denom_str,
    descendant_task_count_str,
    factheirs_str,
    fund_cease_str,
    fund_iota_str,
    fund_onset_str,
    fund_ratio_str,
    fund_share_str,
    gogo_calc_str,
    gogo_want_str,
    healerunit_str,
    knot_str,
    laborheir_str,
    laborunit_str,
    moment_label_str,
    morph_str,
    numor_str,
    plan_label_str,
    problem_bool_str,
    reasonunits_str,
    star_str,
    stop_want_str,
    task_str,
)
from src.a06_belief_logic.test._util.a06_str import (
    factunits_str,
    parent_rope_str,
    planroot_str,
    voices_str,
)
from src.a22_belief_viewer.belief_viewer_app import get_belief_viewer_template


def test_get_belief_viewer_template_ReturnsObj():
    # ESTABLISH / WHEN
    template_str = get_belief_viewer_template()

    # THEN
    assert template_str
    expected_strs_in_template = {
        active_hx_str(),
        active_str(),
        all_voice_cred_str(),
        all_voice_debt_str(),
        awardheirs_str(),
        awardlines_str(),
        chore_str(),
        descendant_task_count_str(),
        factheirs_str(),
        fund_cease_str(),
        fund_onset_str(),
        fund_ratio_str(),
        gogo_calc_str(),
        # _healerunit_ratio_str(),
        # _is_expanded_str(),
        laborheir_str(),
        _level_str(),
        # _range_evaluated_str(),
        _reasonheirs_str(),
        _stop_calc_str(),
        _uid_str(),
        addin_str(),
        awardunits_str(),
        begin_str(),
        moment_label_str(),
        close_str(),
        denom_str(),
        factunits_str(),
        fund_iota_str(),
        fund_share_str(),
        gogo_want_str(),
        # healerunit_str(),
        # knot_str(),
        laborunit_str(),
        morph_str(),
        numor_str(),
        parent_rope_str(),
        voices_str(),
        plan_label_str(),
        planroot_str(),
        # problem_bool_str(),
        reasonunits_str(),
        "root",
        star_str(),
        stop_want_str(),
        task_str(),
        voice_cred_points_str(),
        voice_debt_points_str(),
        # f"voice{memberships_str()}",
        f"voice_{credor_pool_str()}",
        f"voice_{debtor_pool_str()}",
        f"voice_{irrational_voice_debt_points_str()}",
        f"voice_{inallocable_voice_debt_points_str()}",
        f"voice_{fund_give_str()}",
        f"voice_{fund_take_str()}",
        f"voice_{fund_agenda_give_str()}",
        f"voice_{fund_agenda_take_str()}",
        f"voice_{fund_agenda_ratio_give_str()}",
        f"voice_{fund_agenda_ratio_take_str()}",
        f"voice_membership_{group_title_str()}",
        f"voice_membership_{group_cred_points_str()}",
        f"voice_membership_{group_debt_points_str()}",
        f"voice_membership_{credor_pool_str()}",
        f"voice_membership_{debtor_pool_str()}",
        f"voice_membership_{fund_agenda_give_str()}",
        f"voice_membership_{fund_agenda_ratio_give_str()}",
        f"voice_membership_{fund_agenda_ratio_take_str()}",
        f"voice_membership_{fund_agenda_take_str()}",
        f"voice_membership_{fund_give_str()}",
        f"voice_membership_{fund_take_str()}",
    }

    for expected_str in sorted(list(expected_strs_in_template)):
        print(f"{expected_str=}")
        assert template_str.find(expected_str) > 0
