from enum import Enum


class Ch04Keywords(str, Enum):
    FirstLabel = "FirstLabel"
    FundGrain = "FundGrain"
    FundNum = "FundNum"
    GrainNum = "GrainNum"
    GroupTitle = "GroupTitle"
    HealerName = "HealerName"
    INSERT = "INSERT"
    KnotTerm = "KnotTerm"
    LabelTerm = "LabelTerm"
    MoneyGrain = "MoneyGrain"
    MoneyNum = "MoneyNum"
    NameTerm = "NameTerm"
    PoolNum = "PoolNum"
    RespectGrain = "RespectGrain"
    RespectNum = "RespectNum"
    RopeTerm = "RopeTerm"
    TitleTerm = "TitleTerm"
    UPDATE = "UPDATE"
    VoiceName = "VoiceName"
    awardee_title = "awardee_title"
    awardunits = "awardunits"
    belief_name = "belief_name"
    credor_pool = "credor_pool"
    debtor_pool = "debtor_pool"
    fund_agenda_give = "fund_agenda_give"
    fund_agenda_ratio_give = "fund_agenda_ratio_give"
    fund_agenda_ratio_take = "fund_agenda_ratio_take"
    fund_agenda_take = "fund_agenda_take"
    fund_give = "fund_give"
    fund_grain = "fund_grain"
    fund_take = "fund_take"
    give_force = "give_force"
    group_cred_lumen = "group_cred_lumen"
    group_debt_lumen = "group_debt_lumen"
    group_title = "group_title"
    groupunits = "groupunits"
    inallocable_voice_debt_lumen = "inallocable_voice_debt_lumen"
    irrational_voice_debt_lumen = "irrational_voice_debt_lumen"
    knot = "knot"
    laborheir = "laborheir"
    laborunit = "laborunit"
    memberships = "memberships"
    money_grain = "money_grain"
    parent_rope = "parent_rope"
    parent_solo = "parent_solo"
    party_title = "party_title"
    rational = "rational"
    respect_grain = "respect_grain"
    solo = "solo"
    sqlite_datatype = "sqlite_datatype"
    take_force = "take_force"
    voice_cred_lumen = "voice_cred_lumen"
    voice_debt_lumen = "voice_debt_lumen"
    voice_name = "voice_name"

    def __str__(self):
        return self.value
