from src.ch22_belief_viewer._ref.ch22_keywords import (
    Ch02Keywords as wx,
    Ch03Keywords as wx,
    Ch04Keywords as wx,
    Ch06Keywords as wx,
    Ch07Keywords as wx,
    active_hx_str,
    active_str,
    all_voice_cred_str,
    all_voice_debt_str,
    awardheirs_str,
    awardlines_str,
    denom_str,
    descendant_pledge_count_str,
    factheirs_str,
    factunits_str,
    fund_cease_str,
    fund_onset_str,
    fund_ratio_str,
    fund_share_str,
    gogo_calc_str,
    gogo_want_str,
    moment_label_str,
    morph_str,
    numor_str,
    plan_label_str,
    pledge_str,
    reasonheirs_str,
    reasonunits_str,
    star_str,
    stop_calc_str,
    stop_want_str,
    task_str,
    uid_str,
)
from src.ch22_belief_viewer.belief_viewer_app import get_belief_viewer_template


def test_get_belief_viewer_template_ReturnsObj():
    # ESTABLISH / WHEN
    template_str = get_belief_viewer_template()

    # THEN
    assert template_str
    expected_strs_in_template = {
        active_hx_str(),
        active_str(),
        all_voice_cred_str(),
        all_voice_debt_str(),
        awardheirs_str(),
        awardlines_str(),
        task_str(),
        descendant_pledge_count_str(),
        factheirs_str(),
        fund_cease_str(),
        fund_onset_str(),
        fund_ratio_str(),
        gogo_calc_str(),
        # healerunit_ratio_str(),
        # is_expanded_str(),
        wx.laborheir,
        # tree_level_str(),
        # range_evaluated_str(),
        reasonheirs_str(),
        stop_calc_str(),
        uid_str(),
        wx.addin,
        wx.awardunits,
        wx.begin,
        moment_label_str(),
        wx.close,
        denom_str(),
        factunits_str(),
        wx.fund_iota,
        fund_share_str(),
        gogo_want_str(),
        # healerunit_str(),
        # wx.knot,
        wx.laborunit,
        morph_str(),
        numor_str(),
        wx.parent_rope,
        wx.voices,
        plan_label_str(),
        wx.planroot,
        # problem_bool_str(),
        reasonunits_str(),
        "root",
        star_str(),
        stop_want_str(),
        pledge_str(),
        wx.voice_cred_points,
        wx.voice_debt_points,
        # f"voice{wx.memberships}",
        f"voice_{wx.credor_pool}",
        f"voice_{wx.debtor_pool}",
        f"voice_{wx.irrational_voice_debt_points}",
        f"voice_{wx.inallocable_voice_debt_points}",
        f"voice_{wx.fund_give}",
        f"voice_{wx.fund_take}",
        f"voice_{wx.fund_agenda_give}",
        f"voice_{wx.fund_agenda_take}",
        f"voice_{wx.fund_agenda_ratio_give}",
        f"voice_{wx.fund_agenda_ratio_take}",
        f"voice_membership_{wx.group_title}",
        f"voice_membership_{wx.group_cred_points}",
        f"voice_membership_{wx.group_debt_points}",
        f"voice_membership_{wx.credor_pool}",
        f"voice_membership_{wx.debtor_pool}",
        f"voice_membership_{wx.fund_agenda_give}",
        f"voice_membership_{wx.fund_agenda_ratio_give}",
        f"voice_membership_{wx.fund_agenda_ratio_take}",
        f"voice_membership_{wx.fund_agenda_take}",
        f"voice_membership_{wx.fund_give}",
        f"voice_membership_{wx.fund_take}",
    }

    for expected_str in sorted(list(expected_strs_in_template)):
        print(f"{expected_str=}")
        assert template_str.find(expected_str) > 0
