name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install python-semantic-release

      - name: Show current directory and files
        run: |
          pwd
          ls -la
          echo "complete Show current directory and files"

      - name: Run version extractor
        run: |
          echo "start Run version extractor"
          python -c "
          import os, re
          path = '__init__.py'
          print('Working dir:', os.getcwd())
          print('Absolute path:', os.path.abspath(path))
          print('File exists:', os.path.isfile(path))
          with open(path) as f:
              content = f.read()
          match = re.search(r'__version__ *= *[\"\\']([^\"\\']+)', content)
          print(match.group(1) if match else 'No version found')
          "
          echo "complete Run version extractor"

      - name: Create initial tag if missing
        shell: bash
        run: |
          echo "start Create initial tag if missing"
          if ! git describe --tags --abbrev=0 > /dev/null 2>&1; then
            echo "No tags found. Creating initial tag from __version__..."
            VERSION=$(python -c "
          import re
          with open('__init__.py') as f:
              content = f.read()
          match = re.search(r'__version__ *= *[\"\\']([^\"\\']+)', content)
          if match:
              print(match.group(1))
          else:
              raise ValueError('Version not found')
          ")
            git tag "v$VERSION"
            git push origin "v$VERSION"
          else
            echo "Tag found, continuing with release..."
          fi

      - name: Run python-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish
